name: rain-gage
dependencies:
- certifi=2015.9.6.2=py27_0
- decorator=4.0.4=py27_0
- ipykernel=4.1.1=py27_0
- ipython=4.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_0
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.0.3=py27_0
- jupyter_core=4.0.6=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np110py27_1
- mistune=0.7.1=py27_0
- msvc_runtime=1.0.0=vc9_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.0.6=py27_0
- numpy=1.10.1=py27_0
- pandas=0.17.0=np110py27_0
- path.py=8.1.2=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.10.4=py27_1
- pyreadline=2.1=py27_0
- python=2.7.10=3
- python-dateutil=2.4.2=py27_0
- pytz=2015.6=py27_0
- pyzmq=14.7.0=py27_1
- qtconsole=4.1.0=py27_0
- setuptools=18.4=py27_0
- simplegeneric=0.8.1=py27_0
- six=1.10.0=py27_0
- ssl_match_hostname=3.4.0.2=py27_0
- tornado=4.2.1=py27_0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6

